robot_name: "limo0"

# Time Step (dt)
dt: 0.001  
# Physical radius of the Limo robot (meters)
robot_radius: 0.22  

# Extra buffer distance kept from obstacles (meters)
safety_margin: 0.05 

# Resolution for polygon rounding in Clipper2 (meters)
inflation_epsilon: 0.01

# Maximum linear velocity (m/s)
# Used to generate the timed reference trajectory
v_max: 0.5 

# Maximum curvature (1/turning_radius)
# curvature_max = 1.0 means Min Turning Radius = 1.0m
curvature_max: 1.0 

max_shortcut_distance: 1
min_radius: 0.4
step_size: 0.05
t_max: 400

# --- Probabilistic Roadmap (PRM) ---
prm:
  n_samples: 400        # Number of random nodes to scatter
  #connection_radius: 2.0   # Max distance to connect two nodes
  #k_neighbors: 15    # Max neighbors to check for connection
  min_connection_distance: 1.6  # 4 * min_radius (0.4) = 1.6m
  max_connection_distance: 7.0  # Prevents edges that are too long/risky
  resolution: 0.05

# --- Exact Cell Decomposition Planner ---
ecd:
  heuristic_weight: 1.0

# --- Approximate Cell Decomposition Planner ---
acd:
  quadtree_max_depth: 6
  quadtree_min_size: 0.2
  k_victim_neighbors: 15
  